class PersonExists(Exception):
    pass


class AppointmentExists(Exception):
    pass